---

alignment:
  R: "01"
  u: "NEAR"
  a: 0 
  A: 10 
  b: 15 
  B: 7 
  S: 1  
  f: "BlastTab+"

parsdepth:
  al: 100 
  tl: 50 
  pd: 3 
  id: 75

pcratio:
  ad: 50 
  id: 75

split:
  pc: 8 
  dp: 0 
  sl: 100

