---

alignment:
  R: "01"
  u: "NEAR"
  a: 0 
  A: 10 
  b: 15 
  B: 7 
  S: 1  
  f: "BlastTab+"

parsdepth:
  al: 100 
  tl: 50 
  pd: 1 
  id: 75

pcratio:
  ad: 50 
  id: 75

mpc:
  sp: "false"
  rf: "lambda.fasta"
  R: "01"
  u: "NEAR"
  a: 8
  A: 16 
  b: 12 
  B: 5
  S: 1  
  f: "BlastTab+"
  id: 95
  al: 50
  lt: 50

split:
  pc: 10
  dp: 0 
  sl: 100
