---

alignment:
  R: "01"
  u: "NEAR"
  a: 8 
  A: 16 
  b: 12 
  B: 5 
  S: 1  
  f: "BlastTab+"

parsdepth:
  al: 100 
  tl: 50 
  pd: 5 
  id: 75

pcratio:
  ad: 50 
  id: 75

split:
  pc: 10 
  dp: 10 
  sl: 100

